export interface Project {
  id: string;
  title: string;
  domain: string;
  image: string;
}

export const projects: Project[] = [
  { id: "abogadoscontreras", title: "Abogados Contreras", domain: "abogadoscontreras.es", image: "/images/projects/abogadoscontreras.webp" },
  { id: "acedocalderon", title: "Acedo Calderon", domain: "acedocalderon.es", image: "/images/projects/acedocalderon.webp" },
  { id: "activatours", title: "Activa Tours", domain: "activatours.es", image: "/images/projects/activatours.webp" },
  { id: "agustinhipolitotomas", title: "Agustin Hipolito Tomas", domain: "agustinhipolitotomas.com", image: "/images/projects/agustinhipolitotomas.webp" },
  { id: "alanfruits", title: "Alan Fruits", domain: "alanfruits.com", image: "/images/projects/alanfruits.webp" },
  { id: "alangetermal", title: "Alange Termal", domain: "alangetermal.com", image: "/images/projects/alangetermal.webp" },
  { id: "aletheiapsicologos", title: "Aletheia Psicologos", domain: "aletheiapsicologos.com", image: "/images/projects/aletheiapsicologos.webp" },
  { id: "anabasterra", title: "Ana Basterra", domain: "anabasterra.com", image: "/images/projects/anabasterra.webp" },
  { id: "aovealanfruits", title: "AOVE Alan Fruits", domain: "aovealanfruits.es", image: "/images/projects/aovealanfruits.webp" },
  { id: "apartamentosimpluvium", title: "Apartamentos Impluvium", domain: "apartamentosimpluvium.com", image: "/images/projects/apartamentosimpluvium.webp" },
  { id: "asantecafeteria", title: "Asante Cafeteria", domain: "asantecafeteria.es", image: "/images/projects/asantecafeteria.webp" },
  { id: "asesoresemerita", title: "Asesores Emerita", domain: "asesoresemerita.es", image: "/images/projects/asesoresemerita.webp" },
  { id: "autocaravanasmyriam", title: "Autocaravanas Myriam", domain: "autocaravanasmyriam.es", image: "/images/projects/autocaravanasmyriam.webp" },
  { id: "autocaresgonzalezmancha", title: "Autocares Gonzalez Mancha", domain: "autocaresgonzalezmancha.es", image: "/images/projects/autocaresgonzalezmancha.webp" },
  { id: "badabox", title: "Badabox", domain: "badabox.es", image: "/images/projects/badabox.webp" },
  { id: "beaconpsicologia", title: "Beacon Psicologia", domain: "beaconpsicologia.es", image: "/images/projects/beaconpsicologia.webp" },
  { id: "braseriaaugusta", title: "Braseria Augusta", domain: "braseriaaugusta.es", image: "/images/projects/braseriaaugusta.webp" },
  { id: "cartoex", title: "Cartoex", domain: "cartoex.es", image: "/images/projects/cartoex.webp" },
  { id: "casasecoboxmodular", title: "Casaseco Box Modular", domain: "casasecoboxmodular.com", image: "/images/projects/casasecoboxmodular.webp" },
  { id: "caybacb", title: "Caybacb", domain: "caybacb.com", image: "/images/projects/caybacb.webp" },
  { id: "centroatlaspuebla", title: "Centro Atlas Puebla", domain: "centroatlaspuebla.es", image: "/images/projects/centroatlaspuebla.webp" },
  { id: "clinicapies", title: "Clinica Pies", domain: "clinicapies.com", image: "/images/projects/clinicapies.webp" },
  { id: "clinvetmercedesgrande", title: "Clinvet Mercedes Grande", domain: "clinvetmercedesgrande.es", image: "/images/projects/clinvetmercedesgrande.webp" },
  { id: "elisabethcasablanca", title: "Elisabeth Casablanca", domain: "elisabethcasablanca.es", image: "/images/projects/elisabethcasablanca.webp" },
  { id: "elsitiodemire-creo", title: "El Sitio de Mire Creo", domain: "elsitiodemire-creo.es", image: "/images/projects/elsitiodemire-creo.webp" },
  { id: "emeritaasesores", title: "Emerita Asesores", domain: "emeritaasesores.es", image: "/images/projects/emeritaasesores.webp" },
  { id: "espaziomerida", title: "Espazio Merida", domain: "espaziomerida.com", image: "/images/projects/espaziomerida.webp" },
  { id: "esterpulidoabogada", title: "Ester Pulido Abogada", domain: "esterpulidoabogada.es", image: "/images/projects/esterpulidoabogada.webp" },
  { id: "excavacionesmoreno", title: "Excavaciones Moreno", domain: "excavacionesmoreno.es", image: "/images/projects/excavacionesmoreno.webp" },
  { id: "extremaduraentudedo", title: "Extremadura en tu Dedo", domain: "extremaduraentudedo.com", image: "/images/projects/extremaduraentudedo.webp" },
  { id: "extrenatura", title: "Extrenatura", domain: "extrenatura.es", image: "/images/projects/extrenatura.webp" },
  { id: "fcotrinidad", title: "Fco Trinidad", domain: "fcotrinidad.com", image: "/images/projects/fcotrinidad.webp" },
  { id: "gestaltmerida", title: "Gestalt Merida", domain: "gestaltmerida.com", image: "/images/projects/gestaltmerida.webp" },
  { id: "gloriabenditaextremadura", title: "Gloria Bendita Extremadura", domain: "gloriabenditaextremadura.com", image: "/images/projects/gloriabenditaextremadura.webp" },
  { id: "gourmetsani", title: "Gourmet Sani", domain: "gourmetsani.com", image: "/images/projects/gourmetsani.webp" },
  { id: "hfdomolarex", title: "HF Domo Larex", domain: "hfdomolarex.com", image: "/images/projects/hfdomolarex.webp" },
  { id: "honnepsicologia", title: "Honne Psicologia", domain: "honnepsicologia.com", image: "/images/projects/honnepsicologia.webp" },
  { id: "inein", title: "Inein", domain: "inein.es", image: "/images/projects/inein.webp" },
  { id: "instalacionestabae", title: "Instalaciones Tabae", domain: "instalacionestabae.es", image: "/images/projects/instalacionestabae.webp" },
  { id: "interioresmeraki", title: "Interiores Meraki", domain: "interioresmeraki.com", image: "/images/projects/interioresmeraki.webp" },
  { id: "jcparquitectura", title: "JCP Arquitectura", domain: "jcparquitectura.es", image: "/images/projects/jcparquitectura.webp" },
  { id: "labaronesa", title: "La Baronesa", domain: "labaronesa.es", image: "/images/projects/labaronesa.webp" },
  { id: "latribunadeljerte", title: "La Tribuna del Jerte", domain: "latribunadeljerte.es", image: "/images/projects/latribunadeljerte.webp" },
  { id: "lavaqui", title: "Lavaqui", domain: "lavaqui.es", image: "/images/projects/lavaqui.webp" },
  { id: "lollipopshop", title: "Lollipop Shop", domain: "lollipopshop.es", image: "/images/projects/lollipopshop.webp" },
  { id: "maderasleon", title: "Maderas Leon", domain: "maderasleon.com", image: "/images/projects/maderasleon.webp" },
  { id: "magaza", title: "Magaza", domain: "magaza.es", image: "/images/projects/magaza.webp" },
  { id: "maribelcarvajal", title: "Maribel Carvajal", domain: "maribelcarvajal.com", image: "/images/projects/maribelcarvajal.webp" },
  { id: "mejoraextremadura", title: "Mejora Extremadura", domain: "mejoraextremadura.es", image: "/images/projects/mejoraextremadura.webp" },
  { id: "milaprieto", title: "Mila Prieto", domain: "milaprieto.com", image: "/images/projects/milaprieto.webp" },
  { id: "mysweetchaos", title: "My Sweet Chaos", domain: "mysweetchaos.es", image: "/images/projects/mysweetchaos.webp" },
  { id: "optimarooms", title: "Optima Rooms", domain: "optimarooms.com", image: "/images/projects/optimarooms.webp" },
  { id: "pazcandomeque", title: "Paz Candomeque", domain: "pazcandomeque.com", image: "/images/projects/pazcandomeque.webp" },
  { id: "pilarvaldelvira", title: "Pilar Valdelvira", domain: "pilarvaldelvira.es", image: "/images/projects/pilarvaldelvira.webp" },
  { id: "pinsaposalud", title: "Pinsapo Salud", domain: "pinsaposalud.es", image: "/images/projects/pinsaposalud.webp" },
  { id: "plataformasmojatierra", title: "Plataformas Mojatierra", domain: "plataformasmojatierra.es", image: "/images/projects/plataformasmojatierra.webp" },
  { id: "premiosnacionalesdelflamenco", title: "Premios Nacionales del Flamenco", domain: "premiosnacionalesdelflamenco.com", image: "/images/projects/premiosnacionalesdelflamenco.webp" },
  { id: "ratiomarketing", title: "Ratio Marketing", domain: "ratiomarketing.es", image: "/images/projects/ratiomarketing.webp" },
];

export const featuredProjects = projects.slice(0, 6);
